### ISSUE TITLE
Autocode Github Login Permissions?

### ISSUE THREAD

**Issue by adonoho** [zappjs/zappjs#29]
Gentlefolk,

The Autocode website asks me to log in with Github and then it wants permission to manipulate my private repos. WoW. I declined the opportunity. Why does Autocode need such privileged access? If they are not necessary, please don't request the permissions.

Anon,
Andrew

**Comment by ctate** [comment]
Hi @adonoho - thanks for reporting this issue. You can use the CLI / Node version (`npm install autocode -g`) without logging in. It's not necessarily necessary for the UI but that's currently how it's designed since it's relies heavily on GitHub and I haven't implemented a robust permissions system yet. I'll do my best to take care of it this week and will follow up asap. Thanks!

**Comment by adonoho** [comment]
First, don't jump through hoops on my account.
Second, letting anyone get access to my private repositories is a non-starter. I suspect I am not alone.
Third, I'm a patient man. Apparently, you're speaking in Austin soon. I'll likely see you then and I'll see what autocoder is about.

**Comment by ctate** [comment]
No biggie - I have a quick fix in mind. I totally get it and you're right: you aren't the only one :) See you at the meetup!

**Comment by Zearin** [comment]
:+1: **(+100!)**

I am interested in this project, and am generally excited whenever I check up on it. But the permissions request for my GitHub login a moment ago just left a bad taste in my mouth.  :/  

- Please don’t harvest my email address.  If I am interested in email updates, I will sign up for them with a  normal form.
- Please don’t snoop into my private repositories.  I made them private for a reason.  I pay money for that feature.  There is no reason Autocode.run needs my private repositories.  Period.
- Please don’t ask for access to my public repositories without telling me *in advance* why you would need such access.  I cannot imagine why the Autocode.run website would need such access, but if there is a good reason, let me make an informed decision.  Don’t spring it on me and hope that I naïvely click the Accept button.

I think Autocode is doing something amazing things, and I want to see it succeed.  Don’t erode my trust before you have earned it!  Neither of us wants that.

**Comment by ctate** [comment]
@Zearin Thanks for the feedback and the continued support. I agree, 110%.

I recently took the main website down and replaced it with the UI, but this is temporary. The UI needs read/write access because it's essentially an IDE for Autocode. It is heavily integrated with GitHub - from loading repos to committing, pushing and releasing versions; so you can generate, build, run and release from one place.

After receiving several requests to allow private repo access, I updated the scope but now I realize how offensive that is to others. I just reduced the permissions to read/write public repos only. This weekend, I will add the ability to completely choose which permissions you wish to allow and communicate why the UI would need to read/write repos - if you choose to give it access. I'll also release the new website which is mostly focused around the CLI / Node module.

Thanks again - I will take care of this asap!

**Comment by Zearin** [comment]
> I'll also release the new website which is mostly focused around the CLI / Node module.

Where is it?

> Thanks again - I will take care of this asap!

How’s it going?

**Comment by ctate** [comment]
Hey @adonoho @Zearin - this project has evolved much over the last few years and has been renamed to ZappJS. It no longer requires GitHub authentication and is fully open source. I'm also working on a VS Code plug-in and other IDEs so you can use Zapp where you normally code. Please check it out and let me know if you have any feedback. Thanks!
